//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTV
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuMuonTra
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PhieuMuonTra()
        {
            this.ChiTietPhieuMuonTras = new HashSet<ChiTietPhieuMuonTra>();
        }
    
        public string MaPhieuMuonTra { get; set; }
        public Nullable<System.DateTime> NgayMuon { get; set; }
        public Nullable<System.DateTime> NgayHenTra { get; set; }
        public Nullable<System.DateTime> NgayTra { get; set; }
        public string SoThe { get; set; }
        public string MaNhanVien { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietPhieuMuonTra> ChiTietPhieuMuonTras { get; set; }
        public virtual DocGia DocGia { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}
